apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default 
  name: faas-idler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: secret-reader
rules:
 - apiGroups: [""] # "" indicates the core API group
   resources: ["secrets"]
   verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: idler-clusterbinding
subjects:
- kind: ServiceAccount
  name: faas-idler
  namespace: default 
roleRef:
  kind: ClusterRole
  name: secret-pod-reader
  apiGroup: rbac.authorization.k8s.io